model:
  huggingface: "QuantTrio/Qwen3-Coder-480B-A35B-Instruct-AWQ"

engine:
  llm:
    tensor_parallel_size: 4
    pipeline_parallel_size: 1
    gpu_memory_utilization: 0.9
    context_length: 16384
    max_concurrent_requests: 512
    vllm:
      image: "vllm/vllm-openai:latest"
      extra_args: "--enable-expert-parallel"

benchmark:
  max_concurrency: 128
  num_prompts: 256
  random_input_len: 8000
  random_output_len: 8000

matrices:
  - deploy.gpu: "NVIDIA H200 141GB"
    deploy.gpu_count: 4
    benchmark.max_concurrency: 256
    benchmark.num_prompts: 512
  - deploy.gpu: "NVIDIA B200"
    deploy.gpu_count: 4
  - deploy.gpu: "NVIDIA H100 80GB"
    deploy.gpu_count: 4
  - deploy.gpu: "NVIDIA RTX PRO 6000 Server Edition"
    deploy.gpu_count: 4
    engine.llm.max_concurrent_requests: 256
    engine.llm.vllm.extra_args: "--enable-expert-parallel"
    benchmark.max_concurrency: 64
    benchmark.num_prompts: 128
