"""Golden matmul configs — known-good ``knobs`` per shape, measured vs cuBLAS.

A *golden config* records, for one matmul shape on one GPU, the autotuned knob
set and the latencies of the deplodock kernel vs cuBLAS (``torch.matmul``). A
config is ``golden`` when deplodock lands within 95% of cuBLAS (or better),
i.e. ``ratio = cublas_us / deplodock_us >= 0.95``.

The set is a ground truth for the tuning **prior**: it pins down what the
planner's first guess *should* land on for canonical shapes, and gives a
deployable-latency baseline to regression-test against.

This module is import-light (no torch / cupy at module top) so passes and tests
can read :data:`GOLDEN_CONFIGS` cheaply. The list is regenerated by
``scripts/find_golden_configs.py``, which autotunes each shape, re-benches the
winner at ``-O3`` against cuBLAS, and rewrites the region between the
``BEGIN/END GENERATED`` sentinels below. For the **fp32** configs the reference is
pinned to **true fp32** (``allow_tf32 = False``) so the ratio compares deplodock's
CUDA-core FMA kernel against a real SGEMM, not the ~5-10x faster TF32 tensor-core
path. The **fp16** squares (``*.fp16``) instead ride the warp-tier tensor-core path
and compare against cuBLAS HGEMM (torch's default fp16 matmul) — same tensor-core
hardware on both sides, so the ratio is apples-to-apples vs cuBLAS. On sm_90+ the
autotuner lands these on the swizzled s16816 ``mma_m16n8k16_f16`` (ldmatrix +
mma.sync) atom — the swizzled smem slab avoids shared-load bank conflicts (a
fragment load reading smem opaquely cannot), so mma.sync is the faster fp16
GEMM. On sm_120 the warp-tier prior + greedy now land on a square
**64×64 output tile on a 4-warp CTA with WARP_SPECIALIZE=1** (producer warp issues
TMA, consumer warps run the mma chain), measured at / above cuBLAS across the
squares (2048²: 106.7 µs / 1.06×; 4096²: 746 µs / 1.03×; 1024²: 0.94×). See the
warp-tier block in ``compiler/ir/tile/ir.py:score_tile_geometry``.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# Qwen3-Embedding-0.6B linear dims (mirrors ``tests/perf/cases.py``).
QWEN3_06B_HIDDEN = 1024  # hidden_size
QWEN3_06B_INTER = 3072  # intermediate_size (gate / up / down)
QWEN3_06B_Q_DIM = 2048  # fused Q-projection output (16 heads * 128)
QWEN3_06B_KV_DIM = 1024  # fused K/V-projection output (8 heads * 128)


def matmul_snippet(M: int, N: int, K: int, dtype: str = "fp32") -> str:
    """The torch expression a matmul golden config tunes / benches / reproduces.

    Single source of truth: ``scripts/find_golden_configs.py`` feeds this to
    ``trace_inline_code`` (so the tuned graph *is* this expression), and each
    config reproduces from the same call. fp32 is ``torch.randn``'s default, so
    no dtype kwarg is emitted for fp32 — matching the canonical example
    ``torch.matmul(torch.randn(2048,2048), torch.randn(2048,2048))``.
    """
    if dtype == "fp32":
        return f"torch.matmul(torch.randn({M},{K}), torch.randn({K},{N}))"
    tdt = {"fp16": "torch.float16", "bf16": "torch.bfloat16"}[dtype]
    return f"torch.matmul(torch.randn({M},{K},dtype={tdt}), torch.randn({K},{N},dtype={tdt}))"


def _knobs_env(knobs: dict) -> str:
    """Render a knobs dict as a ``DEPLODOCK_KNOBS`` value: ``BM=8,BN=32,...``."""
    return ",".join(f"{k}={v}" for k, v in knobs.items())


@dataclass(frozen=True, kw_only=True)
class GoldenConfig:
    """A kernel config measured within (or near) cuBLAS on a specific GPU.

    Only the two raw latencies are stored; :attr:`ratio` and :attr:`golden`
    derive from them so the record cannot drift out of sync.
    """

    name: str  # e.g. "square.2048" / "qwen3_06b.q_proj.s128"
    gpu_name: str = "NVIDIA GeForce RTX 5090"
    compute_cap: tuple[int, int] = (12, 0)
    knobs: dict = field(default_factory=dict)  # dict(cuda_op.knobs), verbatim
    deplodock_us: float = 0.0
    cublas_us: float = 0.0

    @property
    def ratio(self) -> float:
        """cuBLAS latency / deplodock latency — 1.0 means parity, >1 means faster."""
        return self.cublas_us / self.deplodock_us if self.deplodock_us else 0.0

    @property
    def golden(self) -> bool:
        """Within 95% of cuBLAS or better."""
        return self.ratio >= 0.95


@dataclass(frozen=True, kw_only=True)
class MatmulGoldenConfig(GoldenConfig):
    """A golden config for a plain 2-D matmul ``(M,K) @ (K,N)``."""

    M: int
    N: int
    K: int
    dtype: str = "fp32"

    def snippet(self) -> str:
        """The torch expression this config tunes / benches / reproduces."""
        return matmul_snippet(self.M, self.N, self.K, self.dtype)

    def repro_command(self, ir: str = "cuda") -> str:
        """A runnable ``deplodock`` command that rebuilds this config's kernel.

        e.g. ``DEPLODOCK_KNOBS="BM=8,..." deplodock compile -c "torch.matmul(...)" --ir cuda``
        """
        return f'DEPLODOCK_KNOBS="{_knobs_env(self.knobs)}" deplodock compile -c "{self.snippet()}" --ir {ir}'


# --- BEGIN GENERATED (scripts/find_golden_configs.py) ---
GOLDEN_CONFIGS: list[GoldenConfig] = [
    MatmulGoldenConfig(
        name="square.512",
        M=512,
        N=512,
        K=512,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 16,
            "BM": 16,
            "FM": 4,
            "FN": 2,
            "BK": 64,
            "SPLITK": 1,
            "BR": 1,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=14.4,
        cublas_us=14.5,
    ),
    MatmulGoldenConfig(
        name="square.1024",
        M=1024,
        N=1024,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 32,
            "BM": 16,
            "FM": 4,
            "FN": 4,
            "BK": 32,
            "SPLITK": 1,
            "BR": 1,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=69.2,
        cublas_us=53.3,
    ),
    MatmulGoldenConfig(
        name="square.2048",
        M=2048,
        N=2048,
        K=2048,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 32,
            "BM": 8,
            "FM": 26,
            "FN": 4,
            "BK": 32,
            "SPLITK": 1,
            "BR": 1,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=294.8,
        cublas_us=296.1,
    ),
    MatmulGoldenConfig(
        name="square.4096",
        M=4096,
        N=4096,
        K=4096,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 32,
            "BM": 16,
            "FM": 10,
            "FN": 4,
            "BK": 32,
            "SPLITK": 1,
            "BR": 1,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=2348.7,
        cublas_us=2144.7,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.q_proj.s32",
        M=32,
        N=2048,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={"BN": 16, "BM": 16, "FM": 1, "FN": 2, "BK": 64, "SPLITK": 1, "BR": 1, "STAGE": "11", "BUFFER_COUNT": 4},
        deplodock_us=14.3,
        cublas_us=12.4,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.kv_proj.s32",
        M=32,
        N=1024,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 16,
            "BM": 8,
            "FM": 2,
            "FN": 2,
            "BK": 64,
            "SPLITK": 2,
            "BR": 1,
            "ATOMIC_FREE_SPLITK": False,
            "STAGE": "11",
            "BUFFER_COUNT": 4,
        },
        deplodock_us=8.2,
        cublas_us=8.3,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.o_proj.s32",
        M=32,
        N=1024,
        K=2048,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 16,
            "BM": 8,
            "FM": 2,
            "FN": 2,
            "BK": 64,
            "SPLITK": 2,
            "BR": 1,
            "ATOMIC_FREE_SPLITK": False,
            "STAGE": "11",
            "BUFFER_COUNT": 4,
        },
        deplodock_us=12.3,
        cublas_us=10.3,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.gate_up_proj.s32",
        M=32,
        N=3072,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 32,
            "BM": 8,
            "FM": 1,
            "FN": 2,
            "BK": 64,
            "SPLITK": 1,
            "BR": 1,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=26.7,
        cublas_us=14.6,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.down_proj.s32",
        M=32,
        N=1024,
        K=3072,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 16,
            "BM": 8,
            "FM": 2,
            "FN": 2,
            "BK": 64,
            "SPLITK": 2,
            "BR": 1,
            "ATOMIC_FREE_SPLITK": False,
            "STAGE": "11",
            "BUFFER_COUNT": 4,
        },
        deplodock_us=16.4,
        cublas_us=14.5,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.q_proj.s128",
        M=128,
        N=2048,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 16,
            "BM": 16,
            "FM": 4,
            "FN": 2,
            "BK": 64,
            "SPLITK": 1,
            "BR": 1,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=26.3,
        cublas_us=20.9,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.kv_proj.s128",
        M=128,
        N=1024,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={"BN": 16, "BM": 8, "FM": 2, "FN": 2, "BK": 64, "SPLITK": 1, "BR": 1, "STAGE": "11", "BUFFER_COUNT": 4},
        deplodock_us=14.4,
        cublas_us=14.5,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.o_proj.s128",
        M=128,
        N=1024,
        K=2048,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 16,
            "BM": 16,
            "FM": 4,
            "FN": 2,
            "BK": 64,
            "SPLITK": 2,
            "BR": 1,
            "ATOMIC_FREE_SPLITK": False,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=28.7,
        cublas_us=19.7,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.gate_up_proj.s128",
        M=128,
        N=3072,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 16,
            "BM": 8,
            "FM": 6,
            "FN": 4,
            "BK": 64,
            "SPLITK": 1,
            "BR": 1,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=30.7,
        cublas_us=39.2,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.down_proj.s128",
        M=128,
        N=1024,
        K=3072,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 16,
            "BM": 16,
            "FM": 4,
            "FN": 2,
            "BK": 64,
            "SPLITK": 2,
            "BR": 1,
            "ATOMIC_FREE_SPLITK": False,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=39.1,
        cublas_us=97.3,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.q_proj.s512",
        M=512,
        N=2048,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={"BN": 64, "BM": 8, "FM": 8, "FN": 2, "BK": 32, "SPLITK": 1, "BR": 1, "STAGE": "11", "BUFFER_COUNT": 2},
        deplodock_us=69.6,
        cublas_us=53.5,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.kv_proj.s512",
        M=512,
        N=1024,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 16,
            "BM": 8,
            "FM": 8,
            "FN": 4,
            "BK": 64,
            "SPLITK": 1,
            "BR": 1,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=38.9,
        cublas_us=41.0,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.o_proj.s512",
        M=512,
        N=1024,
        K=2048,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 64,
            "BM": 8,
            "FM": 8,
            "FN": 2,
            "BK": 32,
            "SPLITK": 2,
            "BR": 1,
            "ATOMIC_FREE_SPLITK": False,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
        },
        deplodock_us=71.8,
        cublas_us=60.3,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.gate_up_proj.s512",
        M=512,
        N=3072,
        K=1024,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 32,
            "BM": 16,
            "FM": 6,
            "FN": 4,
            "BK": 32,
            "SPLITK": 1,
            "BR": 1,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": False,
        },
        deplodock_us=83.4,
        cublas_us=82.2,
    ),
    MatmulGoldenConfig(
        name="qwen3_06b.down_proj.s512",
        M=512,
        N=1024,
        K=3072,
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "BN": 64,
            "BM": 8,
            "FM": 8,
            "FN": 2,
            "BK": 32,
            "SPLITK": 2,
            "BR": 1,
            "ATOMIC_FREE_SPLITK": False,
            "STAGE": "11",
            "BUFFER_COUNT": 2,
        },
        deplodock_us=103.4,
        cublas_us=79.6,
    ),
    MatmulGoldenConfig(
        name="square.512.fp16",
        M=512,
        N=512,
        K=512,
        dtype="fp16",
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "WN": 2,
            "WM": 2,
            "FM": 2,
            "FN": 2,
            "BK": 2,
            "SPLITK": 1,
            "MMA": "mma_m16n8k16_f16",
            "STAGE": "11",
            "BUFFER_COUNT": 4,
        },
        deplodock_us=6.1,
        cublas_us=6.2,
    ),
    MatmulGoldenConfig(
        name="square.1024.fp16",
        M=1024,
        N=1024,
        K=1024,
        dtype="fp16",
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "WN": 4,
            "WM": 1,
            "FM": 4,
            "FN": 2,
            "BK": 2,
            "SPLITK": 1,
            "MMA": "mma_m16n8k16_f16",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": True,
        },
        deplodock_us=18.5,
        cublas_us=17.0,
    ),
    MatmulGoldenConfig(
        name="square.2048.fp16",
        M=2048,
        N=2048,
        K=2048,
        dtype="fp16",
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "WN": 4,
            "WM": 1,
            "FM": 4,
            "FN": 2,
            "BK": 2,
            "SPLITK": 1,
            "MMA": "mma_m16n8k16_f16",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": True,
        },
        deplodock_us=106.7,
        cublas_us=113.0,
    ),
    MatmulGoldenConfig(
        name="square.4096.fp16",
        M=4096,
        N=4096,
        K=4096,
        dtype="fp16",
        gpu_name="NVIDIA GeForce RTX 5090",
        compute_cap=(12, 0),
        knobs={
            "WN": 4,
            "WM": 1,
            "FM": 4,
            "FN": 2,
            "BK": 2,
            "SPLITK": 1,
            "MMA": "mma_m16n8k16_f16",
            "BUFFER_COUNT": 2,
            "WARP_SPECIALIZE": True,
        },
        deplodock_us=746.3,
        cublas_us=765.0,
    ),
]
# --- END GENERATED ---
