model:
  name: "QuantTrio/Qwen3-Coder-30B-A3B-Instruct-AWQ"

backend:
  vllm:
    image: "vllm/vllm-openai:latest"
    tensor_parallel_size: 1
    pipeline_parallel_size: 1
    gpu_memory_utilization: 0.9
    extra_args: "--max-model-len 8192"

variants:
  RTX4090: {}
  RTX5090: {}
  Pro6000: {}
  L40S: {}
