model:
  huggingface: "QuantTrio/Qwen3-Coder-30B-A3B-Instruct-AWQ"

engine:
  llm:
    tensor_parallel_size: 1
    pipeline_parallel_size: 1
    gpu_memory_utilization: 0.9
    context_length: 8192
    vllm:
      image: "vllm/vllm-openai:latest"

benchmark:
  max_concurrency: 128
  num_prompts: 256
  random_input_len: 4000
  random_output_len: 4000

variants:
  RTX4090:
    gpu: "NVIDIA GeForce RTX 4090"
    gpu_count: 1
  RTX5090:
    gpu: "NVIDIA GeForce RTX 5090"
    gpu_count: 1
  Pro6000:
    gpu: "NVIDIA RTX PRO 6000 Server Edition"
    gpu_count: 1
  L40S:
    gpu: "NVIDIA L40S"
    gpu_count: 1
  RTX5090_sglang:
    gpu: "NVIDIA GeForce RTX 5090"
    gpu_count: 1
    engine:
      llm:
        sglang:
          image: "lmsysorg/sglang:latest"
  L40S_sglang:
    gpu: "NVIDIA L40S"
    gpu_count: 1
    engine:
      llm:
        sglang:
          image: "lmsysorg/sglang:latest"
