model:
  name: "ibnzterrell/Meta-Llama-3.3-70B-Instruct-AWQ-INT4"

backend:
  vllm:
    image: "vllm/vllm-openai:latest"
    tensor_parallel_size: 1
    pipeline_parallel_size: 2
    gpu_memory_utilization: 0.9
    extra_args: "--max-model-len 8192 --kv-cache-dtype fp8"

benchmark:
  max_concurrency: 128
  num_prompts: 256
  random_input_len: 4000
  random_output_len: 4000

variants:
  2xRTX4090:
    gpu: "NVIDIA GeForce RTX 4090"
    gpu_count: 2
  2xRTX5090:
    gpu: "NVIDIA GeForce RTX 5090"
    gpu_count: 2
  2xL40S:
    gpu: "NVIDIA L40S"
    gpu_count: 2
    backend:
      vllm:
        pipeline_parallel_size: 1
  Pro6000:
    gpu: "NVIDIA RTX PRO 6000 Workstation Edition"
    gpu_count: 1
    backend:
      vllm:
        pipeline_parallel_size: 1
