model:
  huggingface: "ibnzterrell/Meta-Llama-3.3-70B-Instruct-AWQ-INT4"

engine:
  llm:
    tensor_parallel_size: 1
    pipeline_parallel_size: 2
    gpu_memory_utilization: 0.9
    context_length: 8192
    vllm:
      image: "vllm/vllm-openai:latest"
      extra_args: "--kv-cache-dtype fp8"

benchmark:
  max_concurrency: 128
  num_prompts: 256
  random_input_len: 4000
  random_output_len: 4000

matrices:
  - deploy.gpu: "NVIDIA GeForce RTX 4090"
    deploy.gpu_count: 2
  - deploy.gpu: "NVIDIA GeForce RTX 5090"
    deploy.gpu_count: 2
  - deploy.gpu: "NVIDIA L40S"
    deploy.gpu_count: 2
    engine.llm.pipeline_parallel_size: 1
  - deploy.gpu: "NVIDIA RTX PRO 6000 Workstation Edition"
    deploy.gpu_count: 1
    engine.llm.pipeline_parallel_size: 1
